### ISSUE TITLE
`version` is broken

### ISSUE THREAD

**Issue by emilingerslev** [lunarway/shuttle#9]
Running `shuttle version` crashes with error:

```console
panic: unable to redefine 'c' shorthand in "version" flagset: it's already used for "commit" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc4200a4500, 0xc4200b0fa0)
	/home/travis/gopath/src/github.com/spf13/pflag/flag.go:862 +0x72b
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc4200b0fa0)
	/home/travis/gopath/src/github.com/spf13/pflag/flag.go:875 +0x71
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc4200a4800, 0xc4200f1c10)
	/home/travis/gopath/src/github.com/spf13/pflag/flag.go:278 +0xa0
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc4200a4500, 0xc4200a4800)
	/home/travis/gopath/src/github.com/spf13/pflag/flag.go:873 +0x50
github.com/spf13/cobra.(*Command).mergePersistentFlags(0x148c6e0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:1495 +0x90
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0x148c6e0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:906 +0x2f
github.com/spf13/cobra.(*Command).execute(0x148c6e0, 0x14b0878, 0x0, 0x0, 0x148c6e0, 0x14b0878)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:686 +0x59
github.com/spf13/cobra.(*Command).ExecuteC(0x148c940, 0x13077ec, 0x26, 0x148c6e0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x148c940, 0x1003a8c, 0xc420018118)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/lunarway/shuttle/cmd.Execute()
	/home/travis/gopath/src/github.com/lunarway/shuttle/cmd/root.go:44 +0x31
main.main()
	/home/travis/gopath/src/github.com/lunarway/shuttle/main.go:8 +0x20```

**Comment by emilingerslev** [comment]
Fixed in https://github.com/lunarway/shuttle/commit/6196870e91cc10a77148d600fd1600df7674af66
